runtime: python39
instance_class: F4

# Use custom startup script to install dependencies for Playwright
entrypoint: python initialize.py && gunicorn -b :$PORT app:app

env_variables:
  FLASK_APP: app.py
  FLASK_ENV: production
  FLASK_DEBUG: 0
  CLOUD_ENV: "true"
  PYTHONUNBUFFERED: 1

# Temporary storage mount
volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 1

# Auto-scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_idle_instances: 1
  max_concurrent_requests: 50
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  max_pending_latency: 5000ms

handlers:
  - url: /static
    static_dir: app/static
    secure: always

  - url: /.*
    script: auto
    secure: always
