steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/airtasker-bot:$COMMIT_SHA", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/airtasker-bot:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "airtasker-bot"
      - "--image"
      - "gcr.io/$PROJECT_ID/airtasker-bot:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "2Gi"
      - "--cpu"
      - "2"
      - "--timeout"
      - "3600s"
      - "--set-env-vars"
      - "CLOUD_ENV=true,DISPLAY=:99"

# Store images in Google Container Registry
images:
  - "gcr.io/$PROJECT_ID/airtasker-bot:$COMMIT_SHA"

timeout: "1800s"
